### ISSUE TITLE
自定义部署路径

### ISSUE THREAD

**Issue by jiejianwu** [easy-mock/easy-mock-docker#11]
目前通过docker配置只能部署在根路径下，比如http://127.0.0.1:7300, 但是无法部署在http://127.0.0.12:7300/easymock 下，可否通过docker env支持一下

**Comment by DuanPengfei** [comment]
这种建议在外层做反向代理是处理下比较合适。

**Comment by DuanPengfei** [comment]
如果有确切需求，可以直接提个 PR 😄
