### ISSUE TITLE
搜索团队会报错是什么原因呢？

### ISSUE THREAD

**Issue by hojas** [easy-mock/easy-mock-docker#12]
Error
Internal Server Error

**Comment by DuanPengfei** [comment]
请使用 docker logs tail -100 ${docker_name} 查看下项目代码的真实报错。

**Comment by hojas** [comment]
换了个团队名称就可以了

**Comment by DuanPengfei** [comment]
估计是团队名的某个字符触发了项目代码的 bug，可以去 easymock 的主项目进行反馈下。
