### ISSUE TITLE
docker-compose easymock 镜像版本问题

### ISSUE THREAD

**Issue by del1214** [easy-mock/easy-mock-docker#19]
docker-compose.yml 文件的 easymock 的1.6.1，但提示没有这个版本

docker hub里能找到1.6.1的build记录但是pull不下来，tag里最新的是1.6.0

感谢开源🙏🙏🙏

**Comment by DuanPengfei** [comment]
抱歉，是我的问题，请使用下 1.6.0 版本，可以自己直接改动 docker-compose 里面的版本号，或者使用现在仓库里最新的 docker-compose，已经更新好了。

事情是这样的，之前修复一个 bug 把镜像版本升级为 1.6.1 了，但是因为跟主项目版本号不对应导致很多同学误会了，后删除了 1.6.1 镜像，在 1.6.0 上修复了 bug，由于我的失误，readme 和 docker-compose 里面忘记改动了，抱歉。
