### ISSUE TITLE
Docker 在Centos 7 环境下启动报错

### ISSUE THREAD

**Issue by masonlorain** [easy-mock/easy-mock-docker#2]
**服务器环境:**  
Linux  centos7 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Docker version 17.09.0-ce, build afdb6d4
docker-compose version 1.16.1, build 6d1ac219
**报错如下:**
![Centos 7](https://user-images.githubusercontent.com/26481035/30914100-fb3849ea-a3c4-11e7-8ef0-fbba9274f526.png)
**在 windows 环境下启动正常**
![Windows](https://user-images.githubusercontent.com/26481035/30914121-0d84f83c-a3c5-11e7-9940-2b034a74d112.png)

**Comment by DuanPengfei** [comment]
看起来是文件夹访问权限问题，因为 CentOS 默认是打开 SELinux 的，有很多情况与这个有关，不过从截图中看不出来。

我在 VirtualBox 中安装了 CentOS 7 `3.10.0-693.el7.x86_64`，使用 yum 安装 rpm 包的方式安装了 Docker `version 17.09.0-ce, build afdb6d4`，使用 docker-compose `version 1.16.1, build 6d1ac21` 没有复现错误。

可以在主机 easy-mock 目录和 docker 内 easy-mock 目录执行命令 `id -Z` 和 `ls -ldZ`，然后把结果贴出来看看。

也可以参考一下这些方式看看是否有帮助
[https://github.com/moby/moby/issues/14175](https://github.com/moby/moby/issues/14175)  
[http://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux](http://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux)

**Comment by masonlorain** [comment]
感谢回复，以下为命令结果贴图和做的一些尝试
<hr>

### 命令结果贴图
**主机**
![qq 20170929001811](https://user-images.githubusercontent.com/26481035/30977996-cb393f82-a4ab-11e7-945b-abc6833a5f3d.png)
**docker**
![qq 20170929001726](https://user-images.githubusercontent.com/26481035/30978026-e8fba316-a4ab-11e7-883d-3e0c2e889abf.png)

### 做的一些尝试
尝试使用 mrs 用户启动 `sudo docker-compose up` ，报错和 root 用户下启动相同
尝试不挂载 logs 目录，能启动成功

**Comment by DuanPengfei** [comment]
通过 `id -Z` 结果可以看出系统 SELinux 是关闭状态。我同样把系统 SELinux 关闭后启动新的容器，也没有复现问题。我的 `ls -ldZ` 的结果和你不太一样，我这边如下所示：

![image](https://user-images.githubusercontent.com/4469502/31004895-0829901c-a4bc-11e7-8e44-9301ab0667a9.png)

`ls -Z` 会列出文件安全上下文，可是你这里没有，也看不出什么问题。

现在能想到的做法是在主机上和容器内的 easy-mock 目录下 `ls -al` 查看一下文件拥有者和文件权限。

对于不挂在 logs 目录可以启动成功，有可能是 easy-mock 程序本身会判断文件夹是否存在，不存时自动创建或者不记录日志，没有参与 easy-mock 程序开发，具体就不太清楚了 😂。

**Comment by chuangker** [comment]
[util/log.js#L11-L15](https://github.com/easy-mock/easy-mock/blob/848feb1f7bc4881e29d109255d0dd38300206d74/util/log.js#L11-L15)
```js
const logDir = path.join(__dirname, '../logs')
if (!fs.existsSync(logDir)) {
  mkdirp.sync(logDir)
}
```

**Comment by DuanPengfei** [comment]
😄 果然做了判断，不过虽然不挂载 logs 文件夹可以用，但是日志文件保存调试就不太方便了

**Comment by masonlorain** [comment]
尝试在虚拟机的 Centos 7 系统上使用同样的配置部署，成功了。
尝试在安装了Centos 7 的电脑上使用同样的配置部署，报错和阿里云服务器上的报错一样。
=.=

**Comment by DuanPengfei** [comment]
👌 待今天下班后把家里机器装成 CentOS 7 尝试一下。

**Comment by DuanPengfei** [comment]
家里机器 CentOS 7 没什么问题，十一长假没太关注，等稍有空去阿里云试一下。

**Comment by DuanPengfei** [comment]
后续在我自己的服务器尝试了下，也没有报错出现，issue 暂时关闭了，有后续讨论我们可以再打开。

**Comment by masonlorain** [comment]
好的。如解决报错，我会另外补充。 在2017年12月01日 09:02 ，DuanPengfei写道： 后续在我自己的服务器尝试了下，也没有报错出现，issue 暂时关闭了，有后续讨论我们可以再打开。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by KaierChou** [comment]
遇到同样的问题...不挂载logs才能启动...emmmmmm
