### ISSUE TITLE
docker-compose 部署时报文件权限错误

### ISSUE THREAD

**Issue by songhaoying** [easy-mock/easy-mock-docker#20]
### 环境：
vm 虚拟机：centos7

1. 在 /usr/local/ 下用 sudo mkdir easy-mock新建目录
2. 在easy-mock下用sudo mkdir 分别建立 ./data/db, ./data/redis, ./logs 等目录 与 docker-compose.yml  production.json 配置文件。
3. 使用docker-compose up 装载容器时，web模块报文件权限错误。 mogodb与redis模块可以正常启动。

如图：
 
![image](https://user-images.githubusercontent.com/13110458/59166064-96354580-8b57-11e9-989d-461a3e848ab8.png)

> 我看到git主说宿主机最好不要用root权限来新建目录。但是在/usr/local/目录下只有root权限才能新建目录。

**Comment by vitosong** [comment]
搞定了吗。。我也报同样的错误

**Comment by vitosong** [comment]
将指定的logs目录赋予777权限就可以了。。 chmod 777 /home/root/logs

**Comment by DuanPengfei** [comment]
@howel52 提交的 README 修改已经合并。
