### ISSUE TITLE
docker部署运行出现： net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)

### ISSUE THREAD

**Issue by zhangxin-github** [easy-mock/easy-mock-docker#25]
使用官网提供的docker-compose.yml 运行，启动后无法正常显示界面，
查看network发现出现错误提示： net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)

**Comment by zhangxin-github** [comment]
。。。没有伙伴帮忙吗？

**Comment by K-walker** [comment]
我能够正常运行，没有出现你的问题，但是有个恶心的地方，就是进入他们提供的容器之后，无法使用sudo命令

**Comment by DuanPengfei** [comment]
@zhangxin-github 暂时本地没有复现出来这个报错，有复现流程吗，描述一下吧。

**Comment by DuanPengfei** [comment]
@K-walker 镜像中没有使用 root 用户来操作，在什么场景你需要在容器里面用到 root 呢？

**Comment by K-walker** [comment]
@DuanPengfei 因为我需要配置fe.publicPath 这个参数，但是发现，怎么配置都没用，访问地址还是 localhost:7300 ,我需要加一层路经，比如 我访问  localhost:7300/emock 这个路径是访问首页，其他所有页面都是在这个路径下

**Comment by shaunhua** [comment]
我刚部署好后第一次打开网页也是这个问题。之后我将easy-mock这个container stop掉了，重新start就好了。

**Comment by zsio** [comment]
@K-walker 你可以通过其他服务的反向代理实现这个需求，不要试图改变容器内的配置。

**Comment by Ximu-Luya** [comment]
今天在部署的时候，遇到了和你完全一样的问题，虽然已经过了很久了，希望能帮到之后看到的人。
docker部署好之后直接使用 **域名+端口** 或者 **IP+端口** 访问会出现这个问题，在network里显示vendor.js的status为(failed)，但点开详情它正常返回了200的，在控制台的报错就是你说的这个net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)
如楼上所说，使用反代理即可，我使用了Nginx对服务器绑定的域名进行反代理之后，就正常访问了。
