### ISSUE TITLE
求一个CentOS7.x的docker-compose部署

### ISSUE THREAD

**Issue by xikuang** [easy-mock/easy-mock-docker#6]
如题，希望提供centos7.x的Dockerfile。

**Comment by DuanPengfei** [comment]
个人理解，既然实用 Docker 就是想要它的开箱即用，至于容器里面实用何种系统貌似没有很大的影响。可以说明下需求的出发点吗？如果合理我们会考虑支持的。

**Comment by DuanPengfei** [comment]
如果没有后续问题，此 issue 暂时关闭了。
