### ISSUE TITLE
win10 使用docker部署不成功

### ISSUE THREAD

**Issue by IMMYz** [easy-mock/easy-mock-docker#8]
docker-compose up -d命令后不能成功访问
docker-compose ps中查看状态如下
![qq 20180712153418](https://user-images.githubusercontent.com/11171733/42618972-339051aa-85e9-11e8-8532-a3d101515208.png)
感觉没有正确的启动

**Comment by DuanPengfei** [comment]
可以提供下各个容器的日志吗？
